import { render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { ContributionDonut } from '../charts/Charts'
import { contributors } from '../../test/fixtures'
import { MountainRanking, rankedPeakLayout } from './MountainRanking'

describe('mountain dashboard', () => {
  afterEach(() => vi.unstubAllGlobals())

  it('renders RCI and splits real contributors into Top 4 and Rank 5+', () => { render(<MountainRanking contributors={contributors} mode="RESEARCH_BASELINE" onSelect={() => undefined}/>); expect(screen.getByRole('heading', { name: '领先 TOP4 成员' })).toBeInTheDocument(); const markers = screen.getAllByRole('button', { name: /查看/ }); expect(markers).toHaveLength(4); contributors.slice(0, 4).forEach((contributor) => expect(screen.getByRole('button', { name: new RegExp(contributor.display_name) })).toHaveTextContent(`RCI ${contributor.rci.toFixed(1)}%`)); expect(screen.getByText('Research Baseline')).toBeInTheDocument(); expect(screen.getByText('第 5 名及之后')).toBeInTheDocument(); expect(screen.getByText('05')).toBeInTheDocument() })
  it('maps four descending peak heights to stable anchors and gives numbered gold, silver, and bronze medals only to the top three', () => { const { container } = render(<MountainRanking contributors={contributors} mode="RESEARCH_BASELINE" onSelect={() => undefined}/>); expect(rankedPeakLayout[1].peakY).toBeLessThan(rankedPeakLayout[2].peakY); expect(rankedPeakLayout[2].peakY).toBeLessThan(rankedPeakLayout[3].peakY); expect(rankedPeakLayout[3].peakY).toBeLessThan(rankedPeakLayout[4].peakY); ([['gold', '1'], ['silver', '2'], ['bronze', '3']] as const).forEach(([tone, rank]) => { const medal = container.querySelector(`[data-rank-medal="${tone}"]`); expect(medal).toBeInTheDocument(); expect(medal).toHaveAttribute('data-rank-number', rank); expect(medal).toHaveTextContent(rank) }); expect(container.querySelector('[data-rank-number="4"]')).not.toBeInTheDocument(); expect(container.querySelectorAll('[data-peak-anchor]')).toHaveLength(4) })
  it('assigns medals from rci_rank and moves them when the ranking changes', () => { const changedRanking = [{ ...contributors[0], rci_rank: 2, rci: 27 }, { ...contributors[1], rci_rank: 1, rci: 30 }, ...contributors.slice(2)]; const { rerender } = render(<MountainRanking contributors={changedRanking} mode="CUSTOM_WEIGHTS" onSelect={() => undefined}/>); const firstMarker = screen.getByRole('button', { name: /王五/ }); const secondMarker = screen.getByRole('button', { name: /person-2/ }); expect(firstMarker.querySelector('[data-rank-medal="silver"]')).toBeInTheDocument(); expect(secondMarker.querySelector('[data-rank-medal="gold"]')).toBeInTheDocument(); rerender(<MountainRanking contributors={contributors} mode="RESEARCH_BASELINE" onSelect={() => undefined}/>); expect(screen.getByRole('button', { name: /王五/ }).querySelector('[data-rank-medal="gold"]')).toBeInTheDocument(); expect(screen.getByRole('button', { name: /person-2/ }).querySelector('[data-rank-medal="silver"]')).toBeInTheDocument() })
  it('does not invent markers when fewer than four contributors exist', () => { render(<MountainRanking contributors={contributors.slice(0, 2)} mode="RESEARCH_BASELINE" onSelect={() => undefined}/>); expect(screen.getAllByRole('button', { name: /查看/ })).toHaveLength(2); expect(screen.queryByText('第 5 名及之后')).not.toBeInTheDocument() })
  it('opens a contributor from an accessible marker', async () => { const select = vi.fn(); const user = userEvent.setup(); render(<MountainRanking contributors={contributors} mode="RESEARCH_BASELINE" onSelect={select}/>); await user.click(screen.getByRole('button', { name: /王五/ })); expect(select).toHaveBeenCalledWith(contributors[0]) })
  it('passes the unweighted RCI composition into the donut', () => { render(<ContributionDonut contributor={contributors[0]}/>); expect(screen.getByText('Code Implementation 40')).toBeInTheDocument(); expect(screen.getByText('Pull Request 30')).toBeInTheDocument(); expect(screen.getByText('Issue 20')).toBeInTheDocument(); expect(screen.getByText('Code Review 10')).toBeInTheDocument() })
  it('renders the complete donut immediately when reduced motion is requested', () => { vi.stubGlobal('matchMedia', vi.fn(() => ({ matches: true, media: '(prefers-reduced-motion: reduce)', onchange: null, addListener: vi.fn(), removeListener: vi.fn(), addEventListener: vi.fn(), removeEventListener: vi.fn(), dispatchEvent: vi.fn() }))); const { container } = render(<ContributionDonut contributor={contributors[0]}/>); expect(screen.getByRole('img', { name: /贡献构成/ })).toBeInTheDocument(); expect(container.querySelector('[data-reduced-motion="true"]')).toBeInTheDocument() })
})
