import type { ContributionIndex, Contributor, ContributionEvent, ManagedUser, Overview, RCIContributor, Repository, TimelinePoint } from '../types'

export const repository: Repository = { id: 2, owner: 'demo', name: 'trace', full_name: 'demo/trace', github_repo_id: 22, html_url: 'https://github.com/demo/trace', description: 'Real collaboration', default_branch: 'main', is_private: false, last_sync_at: '2026-09-08T10:00:00Z', created_at: '2026-09-01T00:00:00Z', updated_at: '2026-09-08T10:00:00Z', current_user_role: 'MEMBER' }
export const contributors: (Contributor & RCIContributor)[] = Array.from({ length: 6 }, (_, index) => ({ github_username: `person-${index + 1}`, member_id: index === 0 ? 1 : null, user_id: index === 0 ? 2 : null, display_name: index === 0 ? '王五' : `person-${index + 1}`, is_mapped: index === 0, is_bot: false, rank: index + 1, activity_rank: index + 1, rci_rank: index + 1, rci: 30 - index * 3, total_events: 12 - index, commits: 5, pull_requests: 3, issues: 2, reviews: 2 - Math.min(index, 2), dimension_scores: { code: .4, pr: .3, issue: .2, review: .1 }, composition: { code: 40, pr: 30, issue: 20, review: 10 }, raw_metrics: { effective_commits: 4, raw_commits: 5, filtered_churn: 100, robust_churn: 4.615, merged_prs: 2, effective_issues: 2, effective_reviews: 1 }, weighted_contributions: { code: 10, pr: 7.5, issue: 5, review: 2.5 } }))
export const contributionIndex: ContributionIndex = { repository_id: repository.id, methodology_version: 'RCI_V1', mode: 'RESEARCH_BASELINE', requested_weights: { code: 1, pr: 1, issue: 1, review: 1 }, effective_weights: { code: .25, pr: .25, issue: .25, review: .25 }, active_dimensions: ['code', 'pr', 'issue', 'review'], metric_coverage: { code_churn_coverage: 1, pr_status_coverage: 1, issue_state_reason_coverage: 1, review_metadata_coverage: 1 }, analysis_scope: { description: 'Current bounded synchronized repository data', last_sync_at: repository.last_sync_at }, contributors }
export const timeline: TimelinePoint[] = [{ date: '2026-09-08', total: 12, commits: 5, pull_requests: 3, issues: 2, reviews: 2 }]
export const overview: Overview = { repository, totals: { events: 57, commits: 24, pull_requests: 14, issues: 10, reviews: 9 }, members: 1, mapped_events: 12, unmapped_events: 45, last_sync_at: repository.last_sync_at }
export const events: ContributionEvent[] = [{ id: 1, event_id: 'commit:abc', event_type: 'COMMIT', author_login: 'person-1', member_id: 1, member_display_name: '王五', title: 'Trace the work', github_url: 'https://github.com/demo/trace/commit/abc', event_created_at: '2026-09-08T09:00:00Z', metadata: { sha: 'abcdef123' } }, { id: 2, event_id: 'issue:2', event_type: 'ISSUE', author_login: 'person-1', member_id: 1, member_display_name: '王五', title: 'No external URL', github_url: null, event_created_at: null, metadata: { number: 2 } }]
export const users: ManagedUser[] = [{ id: 1, username: 'admin', display_name: 'Admin', role: 'ADMIN', email: null, is_active: true, created_at: '2026-09-01', email_verified: null }, { id: 2, username: 'member', display_name: 'Member', role: 'MEMBER', email: 'member@example.com', is_active: true, created_at: '2026-09-01', email_verified: true }]
